// Aadrika's English Question Bank - 250 Questions
// Based on i-Ready report analysis - Focus areas: Vocabulary, Informational Text, Building on Phonics strengths

const englishQuestions = [
    // SECTION 1: VOCABULARY (75 questions - Priority area)
    // Sub-focus: Kindergarten-level vocabulary, synonyms/antonyms

    // Basic Vocabulary (30 questions)
    { q: "What is another word for 'big'?", visual: "🐘 Big elephant", choices: ["Small", "Large", "Tiny"], correct: "Large", type: "text" },
    { q: "What does 'happy' mean?", visual: "😊", choices: ["Sad", "Joyful", "Angry"], correct: "Joyful", type: "text" },
    { q: "Which word means the OPPOSITE of hot?", visual: "🔥 vs ❄️", choices: ["Warm", "Cold", "Cool"], correct: "Cold", type: "text" },
    { q: "What is a baby cow called?", visual: "🐄👶", choices: ["Puppy", "Kitten", "Calf"], correct: "Calf", type: "text" },
    { q: "Which word means 'very small'?", visual: "🐭 Tiny mouse", choices: ["Huge", "Tiny", "Big"], correct: "Tiny", type: "text" },
    { q: "What is the opposite of 'up'?", visual: "⬆️ vs ⬇️", choices: ["Over", "Down", "Under"], correct: "Down", type: "text" },
    { q: "What do we call the meal we eat in the morning?", visual: "🌅🍳", choices: ["Lunch", "Dinner", "Breakfast"], correct: "Breakfast", type: "text" },
    { q: "Which word means the same as 'fast'?", visual: "🏃‍♀️ Running", choices: ["Slow", "Quick", "Stop"], correct: "Quick", type: "text" },
    { q: "What is a group of flowers called?", visual: "🌸🌸🌸🌸", choices: ["Bunch", "Pack", "Herd"], correct: "Bunch", type: "text" },
    { q: "Which word is opposite of 'day'?", visual: "☀️ vs 🌙", choices: ["Morning", "Night", "Evening"], correct: "Night", type: "text" },
    { q: "What do we call a person who helps sick people?", visual: "👩‍⚕️", choices: ["Teacher", "Doctor", "Chef"], correct: "Doctor", type: "text" },
    { q: "Which word means the same as 'scared'?", visual: "😨 Scared face", choices: ["Happy", "Afraid", "Excited"], correct: "Afraid", type: "text" },
    { q: "What is the opposite of 'loud'?", visual: "📢 vs 🤫", choices: ["Noisy", "Quiet", "Sound"], correct: "Quiet", type: "text" },
    { q: "What do we use to write?", visual: "✏️📝", choices: ["Fork", "Pencil", "Spoon"], correct: "Pencil", type: "text" },
    { q: "Which word means the same as 'glad'?", visual: "😄 Happy", choices: ["Sad", "Happy", "Mad"], correct: "Happy", type: "text" },
    { q: "What is a baby dog called?", visual: "🐕👶", choices: ["Kitten", "Puppy", "Cub"], correct: "Puppy", type: "text" },
    { q: "What is the opposite of 'wet'?", visual: "💧 vs ☀️", choices: ["Damp", "Dry", "Moist"], correct: "Dry", type: "text" },
    { q: "What do we call the hair on a lion's head?", visual: "🦁", choices: ["Fur", "Mane", "Tail"], correct: "Mane", type: "text" },
    { q: "Which word means the same as 'little'?", visual: "🐰 Small bunny", choices: ["Big", "Small", "Huge"], correct: "Small", type: "text" },
    { q: "What is the opposite of 'old'?", visual: "👴 vs 👶", choices: ["New", "Young", "Fresh"], correct: "Young", type: "text" },
    { q: "What do we call frozen water?", visual: "🧊", choices: ["Steam", "Ice", "Snow"], correct: "Ice", type: "text" },
    { q: "Which word means the same as 'angry'?", visual: "😡 Mad face", choices: ["Happy", "Mad", "Calm"], correct: "Mad", type: "text" },
    { q: "What is a baby cat called?", visual: "🐱👶", choices: ["Puppy", "Kitten", "Cub"], correct: "Kitten", type: "text" },
    { q: "What is the opposite of 'full'?", visual: "🥛 vs 🥛", choices: ["Complete", "Empty", "Half"], correct: "Empty", type: "text" },
    { q: "What do we call a place where animals live in the wild?", visual: "🌳🦁🐘", choices: ["Zoo", "Habitat", "Farm"], correct: "Habitat", type: "text" },
    { q: "Which word means the same as 'sleepy'?", visual: "😴 Tired", choices: ["Awake", "Tired", "Energetic"], correct: "Tired", type: "text" },
    { q: "What is the opposite of 'heavy'?", visual: "🪨 vs 🪶", choices: ["Hard", "Light", "Soft"], correct: "Light", type: "text" },
    { q: "What do we call the sound a dog makes?", visual: "🐕 🗣️", choices: ["Meow", "Bark", "Moo"], correct: "Bark", type: "text" },
    { q: "Which word means the same as 'start'?", visual: "🏁 Starting line", choices: ["End", "Begin", "Stop"], correct: "Begin", type: "text" },
    { q: "What is the opposite of 'soft'?", visual: "🧸 vs 🪨", choices: ["Hard", "Rough", "Smooth"], correct: "Hard", type: "text" },

    // Story/Content Words (25 questions)
    { q: "In a story, who is the main person?", visual: "📚 Story book", choices: ["Setting", "Character", "Plot"], correct: "Character", type: "text" },
    { q: "What do we call where a story happens?", visual: "🏰 Castle setting", choices: ["Character", "Setting", "Problem"], correct: "Setting", type: "text" },
    { q: "What is a 'problem' in a story?", visual: "😟 Story trouble", choices: ["Happy part", "Trouble", "Character"], correct: "Trouble", type: "text" },
    { q: "What do we call the ending of a story?", visual: "📖→📚 Book end", choices: ["Beginning", "Middle", "Ending"], correct: "Ending", type: "text" },
    { q: "Who tells a story?", visual: "📖 Person reading", choices: ["Listener", "Narrator", "Character"], correct: "Narrator", type: "text" },
    { q: "What is the 'title' of a book?", visual: "📚 Book cover", choices: ["Pictures", "Name", "Pages"], correct: "Name", type: "text" },
    { q: "In Frozen, what makes Elsa special?", visual: "❄️ Ice magic", choices: ["Singing", "Magic", "Dancing"], correct: "Magic", type: "text" },
    { q: "What lesson does a story teach?", visual: "📖💡", choices: ["Moral", "Title", "Setting"], correct: "Moral", type: "text" },
    { q: "What do we call made-up stories?", visual: "🦄 Fantasy", choices: ["Real", "Fiction", "News"], correct: "Fiction", type: "text" },
    { q: "What are true stories called?", visual: "📰 Real events", choices: ["Fiction", "Fantasy", "Nonfiction"], correct: "Nonfiction", type: "text" },
    { q: "What do we call the person who wrote the book?", visual: "✍️ Writer", choices: ["Reader", "Author", "Character"], correct: "Author", type: "text" },
    { q: "What happens first in a story?", visual: "📖 Story start", choices: ["Middle", "End", "Beginning"], correct: "Beginning", type: "text" },
    { q: "In stories, what do we call talking animals?", visual: "🐰🗣️ Talking rabbit", choices: ["Real", "Fantasy", "True"], correct: "Fantasy", type: "text" },
    { q: "What is a 'fairy tale'?", visual: "👸🏰 Princess story", choices: ["True story", "Magic story", "Sad story"], correct: "Magic story", type: "text" },
    { q: "Who draws the pictures in books?", visual: "🎨 Book pictures", choices: ["Author", "Illustrator", "Reader"], correct: "Illustrator", type: "text" },
    { q: "What is the 'plot' of a story?", visual: "📚 Story events", choices: ["Characters", "What happens", "Setting"], correct: "What happens", type: "text" },
    { q: "In stories, what is a 'hero'?", visual: "🦸‍♀️ Hero character", choices: ["Bad guy", "Good guy", "Animal"], correct: "Good guy", type: "text" },
    { q: "What do we call the bad character in stories?", visual: "🦹‍♀️ Villain", choices: ["Hero", "Villain", "Friend"], correct: "Villain", type: "text" },
    { q: "What is 'dialogue' in a story?", visual: "💬 Speech bubble", choices: ["Pictures", "Talking", "Setting"], correct: "Talking", type: "text" },
    { q: "What does 'once upon a time' start?", visual: "📖 Fairy tale beginning", choices: ["Poem", "Fairy tale", "Song"], correct: "Fairy tale", type: "text" },
    { q: "In Anna and Elsa's story, what is the castle?", visual: "🏰 Arendelle", choices: ["Character", "Setting", "Problem"], correct: "Setting", type: "text" },
    { q: "What is a 'sequence' in stories?", visual: "1️⃣2️⃣3️⃣ Order", choices: ["Characters", "Order", "Pictures"], correct: "Order", type: "text" },
    { q: "What does 'happily ever after' mean?", visual: "😊🏰 Happy ending", choices: ["Sad ending", "Happy ending", "Beginning"], correct: "Happy ending", type: "text" },
    { q: "What is a 'chapter' in a book?", visual: "📚 Book section", choices: ["Picture", "Section", "Cover"], correct: "Section", type: "text" },
    { q: "In stories, what is 'conflict'?", visual: "⚔️ Story conflict", choices: ["Peace", "Problem", "Solution"], correct: "Problem", type: "text" },

    // Action Words (20 questions)
    { q: "What does 'run' mean?", visual: "🏃‍♀️ Running", choices: ["Walk slow", "Move fast", "Stand still"], correct: "Move fast", type: "text" },
    { q: "What does 'jump' mean?", visual: "🦘 Jumping", choices: ["Crawl", "Leap up", "Sit down"], correct: "Leap up", type: "text" },
    { q: "What does 'whisper' mean?", visual: "🤫 Quiet talking", choices: ["Yell loud", "Talk quiet", "Sing"], correct: "Talk quiet", type: "text" },
    { q: "What does 'crawl' mean?", visual: "👶 Baby crawling", choices: ["Walk", "Move on hands/knees", "Jump"], correct: "Move on hands/knees", type: "text" },
    { q: "What does 'laugh' mean?", visual: "😂 Laughing", choices: ["Cry", "Show happiness", "Sleep"], correct: "Show happiness", type: "text" },
    { q: "What does 'catch' mean?", visual: "🤾‍♀️ Catching ball", choices: ["Throw", "Grab", "Drop"], correct: "Grab", type: "text" },
    { q: "What does 'swim' mean?", visual: "🏊‍♀️ Swimming", choices: ["Run on land", "Move in water", "Fly"], correct: "Move in water", type: "text" },
    { q: "What does 'dance' mean?", visual: "💃 Dancing", choices: ["Sit", "Move to music", "Sleep"], correct: "Move to music", type: "text" },
    { q: "What does 'hide' mean?", visual: "🙈 Hiding", choices: ["Show", "Stay out of sight", "Run"], correct: "Stay out of sight", type: "text" },
    { q: "What does 'climb' mean?", visual: "🧗‍♀️ Climbing", choices: ["Go down", "Go up", "Stay level"], correct: "Go up", type: "text" },
    { q: "What does 'melt' mean?", visual: "🧊→💧 Ice melting", choices: ["Freeze", "Turn to liquid", "Stay solid"], correct: "Turn to liquid", type: "text" },
    { q: "What does 'build' mean?", visual: "🧱 Building blocks", choices: ["Destroy", "Make something", "Break"], correct: "Make something", type: "text" },
    { q: "What does 'grow' mean?", visual: "🌱→🌳 Plant growing", choices: ["Get smaller", "Get bigger", "Stay same"], correct: "Get bigger", type: "text" },
    { q: "What does 'fix' mean?", visual: "🔧 Fixing", choices: ["Break", "Repair", "Hide"], correct: "Repair", type: "text" },
    { q: "What does 'explore' mean?", visual: "🗺️ Exploring", choices: ["Stay home", "Look around", "Sleep"], correct: "Look around", type: "text" },
    { q: "What does 'create' mean?", visual: "🎨 Creating art", choices: ["Destroy", "Make something new", "Copy"], correct: "Make something new", type: "text" },
    { q: "What does 'protect' mean?", visual: "🛡️ Protection", choices: ["Harm", "Keep safe", "Run away"], correct: "Keep safe", type: "text" },
    { q: "What does 'remember' mean?", visual: "🧠 Thinking", choices: ["Forget", "Think of again", "Sleep"], correct: "Think of again", type: "text" },
    { q: "What does 'celebrate' mean?", visual: "🎉 Celebrating", choices: ["Be sad", "Be happy about", "Ignore"], correct: "Be happy about", type: "text" },
    { q: "What does 'imagine' mean?", visual: "💭 Thinking clouds", choices: ["See real things", "Picture in mind", "Forget"], correct: "Picture in mind", type: "text" },

    // SECTION 2: PHONICS REINFORCEMENT (50 questions - Building on strength)
    // Sub-focus: Multisyllabic words, prefixes/suffixes

    // Syllable Practice (25 questions)
    { q: "How many syllables in 'elephant'?", visual: "🐘 E-le-phant", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Clap the syllables in 'butterfly':", visual: "🦋 But-ter-fly", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many parts in 'computer'?", visual: "💻 Com-pu-ter", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count syllables: 'banana'", visual: "🍌 Ba-na-na", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many syllables: 'rainbow'?", visual: "🌈 Rain-bow", choices: ["1", "2", "3"], correct: "2", type: "number" },
    { q: "Clap it out: 'wonderful'", visual: "✨ Won-der-ful", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count the beats: 'hamburger'", visual: "🍔 Ham-bur-ger", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many syllables: 'amazing'?", visual: "🤩 A-ma-zing", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Syllables in 'basketball':", visual: "🏀 Bas-ket-ball", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count parts: 'grandfather'", visual: "👴 Grand-fa-ther", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many syllables: 'yesterday'?", visual: "📅 Yes-ter-day", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Clap: 'telephone'", visual: "📞 Tel-e-phone", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Syllables in 'dinosaur':", visual: "🦕 Di-no-saur", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count beats: 'umbrella'", visual: "☂️ Um-brel-la", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many parts: 'chocolate'?", visual: "🍫 Choc-o-late", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Syllables in 'policeman':", visual: "👮‍♂️ Po-lice-man", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count: 'alligator'", visual: "🐊 Al-li-ga-tor", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "How many syllables: 'remember'?", visual: "🧠 Re-mem-ber", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Clap: 'envelope'", visual: "✉️ En-ve-lope", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Syllables in 'pineapple':", visual: "🍍 Pine-ap-ple", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count beats: 'fantastic'", visual: "🌟 Fan-tas-tic", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "How many parts: 'strawberry'?", visual: "🍓 Straw-ber-ry", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Syllables in 'helicopter':", visual: "🚁 Hel-i-cop-ter", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Count: 'magnificent'", visual: "👑 Mag-nif-i-cent", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "How many syllables: 'watermelon'?", visual: "🍉 Wa-ter-mel-on", choices: ["3", "4", "5"], correct: "4", type: "number" },

    // Word Parts (25 questions)
    { q: "What does 'un-' mean in 'unhappy'?", visual: "😢 Un-happy", choices: ["Very", "Not", "Again"], correct: "Not", type: "text" },
    { q: "What does 're-' mean in 'rebuild'?", visual: "🔨 Re-build", choices: ["Not", "Again", "Before"], correct: "Again", type: "text" },
    { q: "What does '-ing' mean in 'playing'?", visual: "⚽ Playing", choices: ["Past", "Now", "Future"], correct: "Now", type: "text" },
    { q: "What does '-ed' mean in 'jumped'?", visual: "🦘 Jumped", choices: ["Now", "Past", "Future"], correct: "Past", type: "text" },
    { q: "Find the root word in 'runner':", visual: "🏃‍♂️ Run-ner", choices: ["Run", "Ner", "Runner"], correct: "Run", type: "text" },
    { q: "What does '-er' mean in 'teacher'?", visual: "👩‍🏫 Teach-er", choices: ["Thing", "Person who", "Place"], correct: "Person who", type: "text" },
    { q: "Root word in 'singing':", visual: "🎤 Sing-ing", choices: ["Sing", "Ing", "Song"], correct: "Sing", type: "text" },
    { q: "What does 'pre-' mean in 'preview'?", visual: "👀 Pre-view", choices: ["After", "Before", "During"], correct: "Before", type: "text" },
    { q: "Find the root in 'helpful':", visual: "🤝 Help-ful", choices: ["Help", "Ful", "Helpful"], correct: "Help", type: "text" },
    { q: "What does '-ful' mean in 'colorful'?", visual: "🌈 Color-ful", choices: ["Without", "Full of", "Small"], correct: "Full of", type: "text" },
    { q: "Root word in 'walked':", visual: "🚶‍♀️ Walk-ed", choices: ["Walk", "Ed", "Walking"], correct: "Walk", type: "text" },
    { q: "What does '-less' mean in 'hopeless'?", visual: "😔 Hope-less", choices: ["Full of", "Without", "Small"], correct: "Without", type: "text" },
    { q: "Find the root in 'kindness':", visual: "💝 Kind-ness", choices: ["Kind", "Ness", "Kindness"], correct: "Kind", type: "text" },
    { q: "What does '-ness' mean in 'darkness'?", visual: "🌑 Dark-ness", choices: ["State of", "Not", "Again"], correct: "State of", type: "text" },
    { q: "Root word in 'careful':", visual: "⚠️ Care-ful", choices: ["Care", "Ful", "Careful"], correct: "Care", type: "text" },
    { q: "What does 'un-' do to words?", visual: "🔄 Opposite", choices: ["Makes bigger", "Makes opposite", "Makes past"], correct: "Makes opposite", type: "text" },
    { q: "Find the root in 'sailor':", visual: "⛵ Sail-or", choices: ["Sail", "Or", "Sailor"], correct: "Sail", type: "text" },
    { q: "What does '-ly' mean in 'quickly'?", visual: "⚡ Quick-ly", choices: ["How", "When", "Where"], correct: "How", type: "text" },
    { q: "Root word in 'reading':", visual: "📚 Read-ing", choices: ["Read", "Ing", "Reading"], correct: "Read", type: "text" },
    { q: "What does 'over-' mean in 'overflow'?", visual: "💧 Over-flow", choices: ["Under", "Too much", "Not enough"], correct: "Too much", type: "text" },
    { q: "Find the root in 'writer':", visual: "✍️ Writ-er", choices: ["Write", "Er", "Writer"], correct: "Write", type: "text" },
    { q: "What does '-est' mean in 'biggest'?", visual: "🐘 Bigg-est", choices: ["Small", "Most", "Less"], correct: "Most", type: "text" },
    { q: "Root word in 'cooking':", visual: "👩‍🍳 Cook-ing", choices: ["Cook", "Ing", "Cooking"], correct: "Cook", type: "text" },
    { q: "What does '-s' mean in 'cats'?", visual: "🐱🐱 Cat-s", choices: ["One", "More than one", "Past"], correct: "More than one", type: "text" },
    { q: "Find the root in 'player':", visual: "🎮 Play-er", choices: ["Play", "Er", "Player"], correct: "Play", type: "text" },

    // SECTION 3: HIGH-FREQUENCY WORDS PRACTICE (50 questions - Building on strength)
    // Sub-focus: Grade 2 high-frequency words, spelling practice

    // Sight Word Recognition (25 questions)
    { q: "Which word means 'also'?", visual: "Plus sign ➕", choices: ["Too", "Two", "To"], correct: "Too", type: "text" },
    { q: "Complete: 'I ___ going to school.'", visual: "🏫 Going to school", choices: ["Am", "Is", "Are"], correct: "Am", type: "text" },
    { q: "Which word fits: 'We ___ playing outside.'", visual: "⚽ Playing outside", choices: ["Was", "Were", "Is"], correct: "Were", type: "text" },
    { q: "Pick the right word: 'The dog ___ brown.'", visual: "🐕 Brown dog", choices: ["Are", "Is", "Am"], correct: "Is", type: "text" },
    { q: "Which is correct: 'I have ___ books.'", visual: "📚 Many books", choices: ["Much", "Many", "More"], correct: "Many", type: "text" },
    { q: "Complete: 'She ___ a good friend.'", visual: "👭 Good friends", choices: ["Are", "Is", "Am"], correct: "Is", type: "text" },
    { q: "Which word means 'before'?", visual: "⏰ Time order", choices: ["After", "First", "Last"], correct: "First", type: "text" },
    { q: "Pick the right: 'They ___ happy.'", visual: "😊 Happy people", choices: ["Is", "Are", "Am"], correct: "Are", type: "text" },
    { q: "Which fits: 'I want ___ go home.'", visual: "🏠 Going home", choices: ["To", "Too", "Two"], correct: "To", type: "text" },
    { q: "Complete: 'The cat ___ sleeping.'", visual: "😴 Sleeping cat", choices: ["Are", "Is", "Am"], correct: "Is", type: "text" },
    { q: "Which word means 'each'?", visual: "👥 Everyone", choices: ["Every", "Some", "Many"], correct: "Every", type: "text" },
    { q: "Pick the right: 'We ___ friends.'", visual: "👫 Being friends", choices: ["Is", "Are", "Am"], correct: "Are", type: "text" },
    { q: "Which fits: 'I have ___ apples.'", visual: "🍎🍎 Two apples", choices: ["To", "Too", "Two"], correct: "Two", type: "text" },
    { q: "Complete: 'The bird ___ flying.'", visual: "🐦 Flying bird", choices: ["Are", "Is", "Am"], correct: "Is", type: "text" },
    { q: "Which word means 'also has'?", visual: "🤲 Also has", choices: ["All", "Always", "Also"], correct: "Also", type: "text" },
    { q: "Pick the right: 'You ___ nice.'", visual: "😊 Being nice", choices: ["Is", "Are", "Am"], correct: "Are", type: "text" },
    { q: "Which fits: 'The ball is ___ big.'", visual: "🏀 Very big ball", choices: ["To", "Too", "Two"], correct: "Too", type: "text" },
    { q: "Complete: 'I ___ six years old.'", visual: "6️⃣ Six years old", choices: ["Is", "Are", "Am"], correct: "Am", type: "text" },
    { q: "Which word means 'during'?", visual: "⏰ During time", choices: ["While", "Before", "After"], correct: "While", type: "text" },
    { q: "Pick the right: 'The dogs ___ barking.'", visual: "🐕🐕 Dogs barking", choices: ["Is", "Are", "Am"], correct: "Are", type: "text" },
    { q: "Which fits: 'Come ___ me.'", visual: "👋 Come with", choices: ["With", "Without", "Within"], correct: "With", type: "text" },
    { q: "Complete: 'The flower ___ pretty.'", visual: "🌸 Pretty flower", choices: ["Are", "Is", "Am"], correct: "Is", type: "text" },
    { q: "Which word means 'made'?", visual: "🔨 Created something", choices: ["Make", "Made", "Making"], correct: "Made", type: "text" },
    { q: "Pick the right: 'The children ___ playing.'", visual: "👶👶 Children playing", choices: ["Is", "Are", "Am"], correct: "Are", type: "text" },
    { q: "Which fits: 'This is ___ book.'", visual: "📖 My book", choices: ["Me", "My", "Mine"], correct: "My", type: "text" },

    // Spelling Practice (25 questions)
    { q: "How do you spell the word for H₂O?", visual: "💧 Liquid to drink", choices: ["Watter", "Water", "Waiter"], correct: "Water", type: "text" },
    { q: "Spell the word for 'not different':", visual: "👯‍♀️ Exactly alike", choices: ["Same", "Sam", "Seem"], correct: "Same", type: "text" },
    { q: "How do you spell 'what we do at night'?", visual: "😴 Nighttime activity", choices: ["Sleep", "Sleap", "Slep"], correct: "Sleep", type: "text" },
    { q: "Spell the opposite of 'go':", visual: "🛑 Stop sign", choices: ["Com", "Come", "Came"], correct: "Come", type: "text" },
    { q: "How do you spell 'past tense of say'?", visual: "🗣️ Past speaking", choices: ["Sed", "Said", "Sayed"], correct: "Said", type: "text" },
    { q: "Spell 'what we use to see':", visual: "👀 Body part", choices: ["Eyes", "Eys", "Eyez"], correct: "Eyes", type: "text" },
    { q: "How do you spell 'more than one child'?", visual: "👶👶👶 Many kids", choices: ["Childrens", "Children", "Childs"], correct: "Children", type: "text" },
    { q: "Spell the word for 'place to live':", visual: "🏠 Where family lives", choices: ["Hous", "House", "Howse"], correct: "House", type: "text" },
    { q: "How do you spell 'opposite of old'?", visual: "👶 Not old", choices: ["Yung", "Young", "Youg"], correct: "Young", type: "text" },
    { q: "Spell 'what we think with':", visual: "🧠 Body part for thinking", choices: ["Brain", "Brane", "Brian"], correct: "Brain", type: "text" },
    { q: "How do you spell 'frozen water'?", visual: "🧊 Cold solid water", choices: ["Ice", "Ise", "Ias"], correct: "Ice", type: "text" },
    { q: "Spell 'opposite of night':", visual: "☀️ When sun shines", choices: ["Day", "Dey", "Dai"], correct: "Day", type: "text" },
    { q: "How do you spell 'what we eat'?", visual: "🍎 Things we eat", choices: ["Food", "Fud", "Foood"], correct: "Food", type: "text" },
    { q: "Spell 'what we read':", visual: "📚 Reading material", choices: ["Book", "Buk", "Boook"], correct: "Book", type: "text" },
    { q: "How do you spell 'opposite of short'?", visual: "📏 Not short", choices: ["Long", "Lung", "Longg"], correct: "Long", type: "text" },
    { q: "Spell 'what we use to walk':", visual: "🦶 Body part", choices: ["Feet", "Feat", "Fet"], correct: "Feet", type: "text" },
    { q: "How do you spell 'opposite of stop'?", visual: "🟢 Keep moving", choices: ["Go", "Goe", "Gow"], correct: "Go", type: "text" },
    { q: "Spell 'what covers our body':", visual: "👗 What we wear", choices: ["Cloths", "Clothes", "Cloes"], correct: "Clothes", type: "text" },
    { q: "How do you spell 'where birds live'?", visual: "🪺 Bird home", choices: ["Nest", "Nist", "Nes"], correct: "Nest", type: "text" },
    { q: "Spell 'what we use to hear':", visual: "👂 Body part", choices: ["Ears", "Ers", "Eers"], correct: "Ears", type: "text" },
    { q: "How do you spell 'baby frog'?", visual: "🐸 Young frog", choices: ["Tadpol", "Tadpole", "Tadpool"], correct: "Tadpole", type: "text" },
    { q: "Spell 'opposite of dark':", visual: "💡 Not dark", choices: ["Light", "Lite", "Ligt"], correct: "Light", type: "text" },
    { q: "How do you spell 'what we breathe'?", visual: "💨 What we breathe", choices: ["Air", "Are", "Aire"], correct: "Air", type: "text" },
    { q: "Spell 'where we learn':", visual: "🏫 Learning place", choices: ["School", "Skool", "Schol"], correct: "School", type: "text" },
    { q: "How do you spell 'opposite of sad'?", visual: "😊 Not sad", choices: ["Hapy", "Happy", "Hapie"], correct: "Happy", type: "text" },

    // SECTION 4: COMPREHENSION: INFORMATIONAL TEXT (50 questions - Priority area)
    // Sub-focus: Main idea, key details, listening comprehension

    // Main Idea Practice (25 questions)
    { q: "A story about different animals at the zoo. What is the main idea?", visual: "🦁🐘🐵 Zoo animals", choices: ["Lions are big", "Zoo has animals", "Elephants eat"], correct: "Zoo has animals", type: "text" },
    { q: "Text about how plants need water and sun. Main idea?", visual: "🌱☀️💧 Plant needs", choices: ["Plants need care", "Water is wet", "Sun is hot"], correct: "Plants need care", type: "text" },
    { q: "Story about different ways to travel. What's the main idea?", visual: "🚗✈️🚢 Transportation", choices: ["Cars are fast", "Many ways to travel", "Planes fly"], correct: "Many ways to travel", type: "text" },
    { q: "Text about keeping teeth healthy. Main idea?", visual: "🦷🪥 Dental care", choices: ["Brushing teeth", "Tooth care", "Toothbrush"], correct: "Tooth care", type: "text" },
    { q: "Story about seasons changing. What's the main idea?", visual: "🌸☀️🍂❄️ Four seasons", choices: ["Winter is cold", "Seasons change", "Leaves fall"], correct: "Seasons change", type: "text" },
    { q: "Text about different farm animals. Main idea?", visual: "🐄🐖🐔 Farm animals", choices: ["Cows give milk", "Animals live on farms", "Pigs are pink"], correct: "Animals live on farms", type: "text" },
    { q: "Story about safety rules. What's the main idea?", visual: "⛑️🚦⚠️ Safety", choices: ["Wear helmets", "Follow safety rules", "Red means stop"], correct: "Follow safety rules", type: "text" },
    { q: "Text about how bees make honey. Main idea?", visual: "🐝🍯 Bee work", choices: ["Bees are busy", "How bees make honey", "Honey is sweet"], correct: "How bees make honey", type: "text" },
    { q: "Story about different weather. What's the main idea?", visual: "☀️🌧️❄️ Weather types", choices: ["Rain is wet", "Weather changes", "Snow is white"], correct: "Weather changes", type: "text" },
    { q: "Text about recycling. Main idea?", visual: "♻️🗂️ Recycling", choices: ["Paper is useful", "Help the Earth", "Cans are metal"], correct: "Help the Earth", type: "text" },
    { q: "Story about different foods. What's the main idea?", visual: "🍎🥕🍞 Various foods", choices: ["Apples are red", "Many food types", "Bread is soft"], correct: "Many food types", type: "text" },
    { q: "Text about exercise. Main idea?", visual: "🏃‍♀️🤸‍♀️ Exercise", choices: ["Running is fun", "Exercise helps health", "Jumping is high"], correct: "Exercise helps health", type: "text" },
    { q: "Story about different homes. What's the main idea?", visual: "🏠🏢🏡 Different homes", choices: ["Houses are big", "People live differently", "Apartments are tall"], correct: "People live differently", type: "text" },
    { q: "Text about community helpers. Main idea?", visual: "👮‍♀️🚒👩‍⚕️ Helpers", choices: ["Police help us", "People help community", "Doctors are kind"], correct: "People help community", type: "text" },
    { q: "Story about ocean animals. What's the main idea?", visual: "🐟🦈🐙 Ocean life", choices: ["Fish can swim", "Ocean has animals", "Sharks are big"], correct: "Ocean has animals", type: "text" },
    { q: "Text about friendship. Main idea?", visual: "👫🤝 Friendship", choices: ["Friends play together", "How to be a friend", "Sharing is nice"], correct: "How to be a friend", type: "text" },
    { q: "Story about different colors. What's the main idea?", visual: "🔴🟢🔵 Colors", choices: ["Red is bright", "Colors are everywhere", "Blue is cool"], correct: "Colors are everywhere", type: "text" },
    { q: "Text about baby animals. Main idea?", visual: "🐶🐱🐣 Baby animals", choices: ["Puppies are cute", "Animals have babies", "Kittens are small"], correct: "Animals have babies", type: "text" },
    { q: "Story about different jobs. What's the main idea?", visual: "👩‍🍳👨‍🔬👩‍🏫 Jobs", choices: ["Cooks make food", "People have jobs", "Teachers help learn"], correct: "People have jobs", type: "text" },
    { q: "Text about water cycle. Main idea?", visual: "💧☁️🌧️ Water cycle", choices: ["Rain falls down", "Water moves around", "Clouds are fluffy"], correct: "Water moves around", type: "text" },
    { q: "Story about different shapes in nature. Main idea?", visual: "🌕⭐🌈 Natural shapes", choices: ["Moon is round", "Shapes in nature", "Stars twinkle"], correct: "Shapes in nature", type: "text" },
    { q: "Text about musical instruments. Main idea?", visual: "🎸🥁🎹 Instruments", choices: ["Guitars have strings", "Instruments make music", "Drums are loud"], correct: "Instruments make music", type: "text" },
    { q: "Story about different textures. What's the main idea?", visual: "🧸🪨🧊 Textures", choices: ["Teddy bears are soft", "Things feel different", "Rocks are hard"], correct: "Things feel different", type: "text" },
    { q: "Text about healthy eating. Main idea?", visual: "🥗🍎🥛 Healthy food", choices: ["Salads have greens", "Eat healthy foods", "Milk has calcium"], correct: "Eat healthy foods", type: "text" },
    { q: "Story about different sounds. What's the main idea?", visual: "🔔🎵🚁 Various sounds", choices: ["Bells ring loudly", "Sounds are everywhere", "Music is pretty"], correct: "Sounds are everywhere", type: "text" },

    // Key Details Practice (25 questions)
    { q: "Text says: 'Dogs bark, cats meow, birds chirp.' What do cats do?", visual: "🐱 Cat sound", choices: ["Bark", "Meow", "Chirp"], correct: "Meow", type: "text" },
    { q: "Story: 'Red apples, green grass, blue sky.' What color is grass?", visual: "🌱 Grass color", choices: ["Red", "Green", "Blue"], correct: "Green", type: "text" },
    { q: "Text: 'Butterflies have wings, bees make honey, ants work hard.' What do bees make?", visual: "🐝 Bee product", choices: ["Wings", "Honey", "Work"], correct: "Honey", type: "text" },
    { q: "Story: 'Bears sleep in winter, birds fly south, squirrels gather nuts.' What do squirrels do?", visual: "🐿️ Squirrel activity", choices: ["Sleep", "Fly south", "Gather nuts"], correct: "Gather nuts", type: "text" },
    { q: "Text: 'Fire trucks are red, school buses are yellow, police cars are black and white.' What color are school buses?", visual: "🚌 School bus color", choices: ["Red", "Yellow", "Black and white"], correct: "Yellow", type: "text" },
    { q: "Story: 'Roses smell sweet, garbage smells bad, cookies smell good.' How do roses smell?", visual: "🌹 Rose smell", choices: ["Bad", "Sweet", "Good"], correct: "Sweet", type: "text" },
    { q: "Text: 'Ice is cold, fire is hot, water is wet.' What is fire?", visual: "🔥 Fire temperature", choices: ["Cold", "Hot", "Wet"], correct: "Hot", type: "text" },
    { q: "Story: 'Elephants are big, mice are small, horses are medium.' How big are mice?", visual: "🐭 Mouse size", choices: ["Big", "Small", "Medium"], correct: "Small", type: "text" },
    { q: "Text: 'Lions roar, lambs baa, ducks quack.' What sound do ducks make?", visual: "🦆 Duck sound", choices: ["Roar", "Baa", "Quack"], correct: "Quack", type: "text" },
    { q: "Story: 'Morning comes first, afternoon is next, evening is last.' What comes first?", visual: "🌅 Time order", choices: ["Afternoon", "Morning", "Evening"], correct: "Morning", type: "text" },
    { q: "Text: 'Fish swim, birds fly, dogs walk.' How do fish move?", visual: "🐟 Fish movement", choices: ["Swim", "Fly", "Walk"], correct: "Swim", type: "text" },
    { q: "Story: 'Summer is warm, winter is cold, spring is mild.' What is winter like?", visual: "❄️ Winter weather", choices: ["Warm", "Cold", "Mild"], correct: "Cold", type: "text" },
    { q: "Text: 'Apples grow on trees, carrots grow underground, grass grows on ground.' Where do carrots grow?", visual: "🥕 Carrot location", choices: ["On trees", "Underground", "On ground"], correct: "Underground", type: "text" },
    { q: "Story: 'Doctors help sick people, teachers help students learn, firefighters help with fires.' Who helps students?", visual: "👩‍🏫 Student helper", choices: ["Doctors", "Teachers", "Firefighters"], correct: "Teachers", type: "text" },
    { q: "Text: 'Circles are round, squares have corners, triangles have three sides.' What shape is round?", visual: "⭕ Round shape", choices: ["Square", "Circle", "Triangle"], correct: "Circle", type: "text" },
    { q: "Story: 'Milk comes from cows, eggs come from chickens, honey comes from bees.' Where do eggs come from?", visual: "🥚 Egg source", choices: ["Cows", "Chickens", "Bees"], correct: "Chickens", type: "text" },
    { q: "Text: 'Pencils write, erasers erase, rulers measure.' What do erasers do?", visual: "📏 Eraser function", choices: ["Write", "Erase", "Measure"], correct: "Erase", type: "text" },
    { q: "Story: 'Monday starts the week, Friday ends work, Sunday is rest day.' What day is for rest?", visual: "📅 Rest day", choices: ["Monday", "Friday", "Sunday"], correct: "Sunday", type: "text" },
    { q: "Text: 'Cars drive on roads, boats sail on water, planes fly in sky.' Where do boats sail?", visual: "⛵ Boat location", choices: ["Roads", "Water", "Sky"], correct: "Water", type: "text" },
    { q: "Story: 'Breakfast is morning meal, lunch is noon meal, dinner is evening meal.' What is the noon meal?", visual: "🍽️ Noon meal", choices: ["Breakfast", "Lunch", "Dinner"], correct: "Lunch", type: "text" },
    { q: "Text: 'Libraries have books, kitchens have food, bedrooms have beds.' What do libraries have?", visual: "📚 Library contents", choices: ["Food", "Books", "Beds"], correct: "Books", type: "text" },
    { q: "Story: 'Socks go on feet, hats go on heads, gloves go on hands.' Where do hats go?", visual: "👒 Hat placement", choices: ["Feet", "Heads", "Hands"], correct: "Heads", type: "text" },
    { q: "Text: 'Toothbrushes clean teeth, soap cleans hands, shampoo cleans hair.' What cleans hair?", visual: "🧴 Hair cleaner", choices: ["Toothbrush", "Soap", "Shampoo"], correct: "Shampoo", type: "text" },
    { q: "Story: 'Spring has flowers, summer has heat, fall has colorful leaves.' What does spring have?", visual: "🌸 Spring feature", choices: ["Heat", "Flowers", "Colorful leaves"], correct: "Flowers", type: "text" },
    { q: "Text: 'Bees live in hives, birds live in nests, fish live in water.' Where do birds live?", visual: "🐦 Bird home", choices: ["Hives", "Nests", "Water"], correct: "Nests", type: "text" },

    // SECTION 5: COMPREHENSION: LITERATURE (25 questions - Building on improvement)
    // Sub-focus: Story elements, retelling

    // Story Elements (15 questions)
    { q: "In 'Three Little Pigs', who is the main character?", visual: "🐷🐷🐷 Three pigs", choices: ["Wolf", "Pigs", "House"], correct: "Pigs", type: "text" },
    { q: "Where does 'Goldilocks' take place?", visual: "🏠 Bear's house", choices: ["Forest house", "Castle", "School"], correct: "Forest house", type: "text" },
    { q: "In 'Little Red Riding Hood', what is the problem?", visual: "🐺 Wolf danger", choices: ["Lost hood", "Bad wolf", "No food"], correct: "Bad wolf", type: "text" },
    { q: "How does 'Cinderella' end?", visual: "👸 Happy ending", choices: ["Sadly", "Happily", "Scary"], correct: "Happily", type: "text" },
    { q: "Who helps in 'Snow White'?", visual: "👨‍🦲👨‍🦲👨‍🦲 Seven helpers", choices: ["Prince", "Dwarfs", "Animals"], correct: "Dwarfs", type: "text" },
    { q: "Where does 'Jack and the Beanstalk' start?", visual: "🏠 Jack's home", choices: ["Castle", "Jack's home", "Giant's home"], correct: "Jack's home", type: "text" },
    { q: "In 'Frozen', what makes Elsa special?", visual: "❄️ Ice powers", choices: ["Singing", "Ice magic", "Crown"], correct: "Ice magic", type: "text" },
    { q: "What is Anna's problem in 'Frozen'?", visual: "💙 Frozen heart", choices: ["Lost crown", "Frozen heart", "No friends"], correct: "Frozen heart", type: "text" },
    { q: "Who solves problems in 'Frozen'?", visual: "👸👸 Sisters together", choices: ["Olaf", "Sisters", "Kristoff"], correct: "Sisters", type: "text" },
    { q: "How do fairy tales usually end?", visual: "👑✨ Happy ending", choices: ["Sadly", "Happily ever after", "With questions"], correct: "Happily ever after", type: "text" },
    { q: "In 'The Tortoise and the Hare', who wins?", visual: "🐢 vs 🐰 Slow vs fast", choices: ["Hare", "Tortoise", "Both"], correct: "Tortoise", type: "text" },
    { q: "What lesson does 'Tortoise and Hare' teach?", visual: "🐢 Slow and steady", choices: ["Be fast", "Slow and steady wins", "Give up"], correct: "Slow and steady wins", type: "text" },
    { q: "In 'Humpty Dumpty', what happens to Humpty?", visual: "🥚 Broken egg", choices: ["He flies", "He falls", "He dances"], correct: "He falls", type: "text" },
    { q: "Where does 'Rapunzel' live?", visual: "🏰 High tower", choices: ["Forest", "Tower", "Castle"], correct: "Tower", type: "text" },
    { q: "What makes 'Rapunzel' special?", visual: "👩‍🦳 Long hair", choices: ["Magic shoes", "Long hair", "Pretty dress"], correct: "Long hair", type: "text" },

    // Story Sequence and Retelling (10 questions)
    { q: "What happens FIRST in 'Three Bears'?", visual: "🚪 Story beginning", choices: ["Goldilocks sleeps", "Goldilocks enters", "Bears come home"], correct: "Goldilocks enters", type: "text" },
    { q: "What happens AFTER Goldilocks tries the beds?", visual: "😴 After beds", choices: ["She runs away", "Bears come home", "She eats porridge"], correct: "Bears come home", type: "text" },
    { q: "In 'Little Red Riding Hood', what happens BEFORE she meets the wolf?", visual: "🧺 Story start", choices: ["Visits grandma", "Packs basket", "Runs home"], correct: "Packs basket", type: "text" },
    { q: "What happens LAST in 'Three Little Pigs'?", visual: "🏠 Strong house", choices: ["Wolf blows house", "Pigs build houses", "Wolf can't blow brick house"], correct: "Wolf can't blow brick house", type: "text" },
    { q: "In 'Cinderella', what happens AFTER the ball?", visual: "👠 After party", choices: ["Gets dressed", "Loses slipper", "Meets fairy"], correct: "Loses slipper", type: "text" },
    { q: "What happens FIRST in 'Jack and Beanstalk'?", visual: "🌱 Story start", choices: ["Climbs beanstalk", "Trades cow", "Finds giant"], correct: "Trades cow", type: "text" },
    { q: "In 'Frozen', what happens AFTER Elsa runs away?", visual: "❄️ After leaving", choices: ["Anna follows", "Castle freezes", "Olaf appears"], correct: "Anna follows", type: "text" },
    { q: "What happens BEFORE Anna gets frozen heart?", visual: "💙 Before freezing", choices: ["Meets Kristoff", "Elsa's magic hits", "Finds Elsa"], correct: "Elsa's magic hits", type: "text" },
    { q: "What happens LAST in 'Frozen'?", visual: "❄️→☀️ Story end", choices: ["Anna freezes", "Sisters reunite", "Elsa runs away"], correct: "Sisters reunite", type: "text" },
    { q: "In 'Humpty Dumpty', what happens AFTER he falls?", visual: "🥚💔 After fall", choices: ["He climbs again", "Can't be fixed", "He laughs"], correct: "Can't be fixed", type: "text" }
];

module.exports = englishQuestions;