// Aadrika's Math Question Bank - 250 Questions
// Based on i-Ready report analysis - Focus areas: Measurement/Data, Counting to 100, Addition/Subtraction, Basic Shapes

const mathQuestions = [
    // SECTION 1: NUMBER AND OPERATIONS (75 questions)
    // Sub-focus: Counting to 100, Addition/Subtraction concepts

    // Counting to 100 (25 questions)
    { q: "Count the ice crystals. How many are there?", visual: "❄️❄️❄️❄️❄️", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "What number comes after 15?", visual: "15, ?", choices: ["14", "16", "17"], correct: "16", type: "number" },
    { q: "What number comes before 20?", visual: "?, 20", choices: ["18", "19", "21"], correct: "19", type: "number" },
    { q: "Count by 10s: 10, 20, 30, ?", visual: "10️⃣2️⃣0️⃣3️⃣0️⃣?", choices: ["35", "40", "50"], correct: "40", type: "number" },
    { q: "How many snowflakes in total?", visual: "❄️❄️❄️ + ❄️❄️❄️❄️❄️❄️❄️", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "What number is missing: 45, 46, ?, 48", visual: "4️⃣5️⃣ 4️⃣6️⃣ ? 4️⃣8️⃣", choices: ["47", "49", "50"], correct: "47", type: "number" },
    { q: "Count the carrots for Olaf!", visual: "🥕🥕🥕🥕🥕🥕🥕🥕", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "What comes next: 67, 68, 69, ?", visual: "📊 67→68→69→?", choices: ["70", "71", "72"], correct: "70", type: "number" },
    { q: "Count backwards: 25, 24, 23, ?", visual: "25⬇️24⬇️23⬇️?", choices: ["21", "22", "26"], correct: "22", type: "number" },
    { q: "How many tens are in 30?", visual: "30 = ? groups of 10", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Count the magic wands: ", visual: "🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄🪄", choices: ["11", "12", "13"], correct: "12", type: "number" },
    { q: "What number is 1 more than 59?", visual: "59 + 1 = ?", choices: ["58", "60", "61"], correct: "60", type: "number" },
    { q: "Fill in: 80, 81, ?, 83", visual: "8️⃣0️⃣→8️⃣1️⃣→?→8️⃣3️⃣", choices: ["79", "82", "84"], correct: "82", type: "number" },
    { q: "Count by 5s: 5, 10, 15, ?", visual: "5️⃣🔟1️⃣5️⃣?", choices: ["18", "20", "25"], correct: "20", type: "number" },
    { q: "What is 1 less than 91?", visual: "91 - 1 = ?", choices: ["89", "90", "92"], correct: "90", type: "number" },
    { q: "How many crowns?", visual: "👑👑👑👑👑👑👑👑👑👑👑👑👑👑", choices: ["13", "14", "15"], correct: "14", type: "number" },
    { q: "Count from 95 to 98: 95, ?, 97, 98", visual: "95→?→97→98", choices: ["94", "96", "99"], correct: "96", type: "number" },
    { q: "What number comes after 78?", visual: "78 → ?", choices: ["77", "79", "80"], correct: "79", type: "number" },
    { q: "Count by 2s: 2, 4, 6, ?", visual: "2️⃣4️⃣6️⃣?", choices: ["7", "8", "10"], correct: "8", type: "number" },
    { q: "How many groups of 10 in 50?", visual: "50 = ? × 10", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "What number is between 33 and 35?", visual: "33 ? 35", choices: ["32", "34", "36"], correct: "34", type: "number" },
    { q: "Count the castle towers:", visual: "🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰🏰", choices: ["15", "16", "17"], correct: "16", type: "number" },
    { q: "Skip count by 10: 20, 30, ?, 50", visual: "20→30→?→50", choices: ["35", "40", "45"], correct: "40", type: "number" },
    { q: "What's the next number: 88, 89, ?", visual: "88→89→?", choices: ["87", "90", "91"], correct: "90", type: "number" },
    { q: "Count backwards from 100: 100, 99, ?", visual: "100⬇️99⬇️?", choices: ["97", "98", "101"], correct: "98", type: "number" },

    // Addition Concepts (25 questions)
    { q: "Elsa has 3 ice blocks. Anna gives her 2 more. How many total?", visual: "❄️❄️❄️ + ❄️❄️", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "4 + 3 = ?", visual: "🧊🧊🧊🧊 + 🧊🧊🧊", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "Olaf finds 6 sticks. Kristoff gives him 1 more. Total sticks?", visual: "🦴🦴🦴🦴🦴🦴 + 🦴", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "2 + 8 = ?", visual: "🟦🟦 + 🟦🟦🟦🟦🟦🟦🟦🟦", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Anna has 5 flowers. She picks 4 more. How many flowers?", visual: "🌸🌸🌸🌸🌸 + 🌸🌸🌸🌸", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "7 + 2 = ?", visual: "⭐⭐⭐⭐⭐⭐⭐ + ⭐⭐", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "If you have 6 cookies and get 3 more, how many cookies?", visual: "🍪🍪🍪🍪🍪🍪 + 🍪🍪🍪", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "What is 5 + 5?", visual: "🟨🟨🟨🟨🟨 + 🟨🟨🟨🟨🟨", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Sven eats 3 carrots, then 6 more. Total carrots?", visual: "🥕🥕🥕 + 🥕🥕🥕🥕🥕🥕", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "1 + 9 = ?", visual: "🔵 + 🔵🔵🔵🔵🔵🔵🔵🔵🔵", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "There are 4 birds. 5 more come. How many birds now?", visual: "🐦🐦🐦🐦 + 🐦🐦🐦🐦🐦", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "8 + 1 = ?", visual: "🎈🎈🎈🎈🎈🎈🎈🎈 + 🎈", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "Adding zero: 7 + 0 = ?", visual: "🟢🟢🟢🟢🟢🟢🟢 + ⭕", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "Double 4: 4 + 4 = ?", visual: "🟪🟪🟪🟪 + 🟪🟪🟪🟪", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "Anna collects 2 shells, then 7 more. Total shells?", visual: "🐚🐚 + 🐚🐚🐚🐚🐚🐚🐚", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "6 + 4 = ?", visual: "⚫⚫⚫⚫⚫⚫ + ⚫⚫⚫⚫", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Count all: 3 red + 2 blue", visual: "🔴🔴🔴 + 🔵🔵", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "9 + 1 = ?", visual: "🌟🌟🌟🌟🌟🌟🌟🌟🌟 + 🌟", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Elsa makes 5 snowmen. She makes 3 more. Total?", visual: "⛄⛄⛄⛄⛄ + ⛄⛄⛄", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "Double 3: 3 + 3 = ?", visual: "🟨🟨🟨 + 🟨🟨🟨", choices: ["5", "6", "7"], correct: "6", type: "number" },
    { q: "What is 10 + 0?", visual: "🔟 + ⭕", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Count all the hearts: 4 + 6", visual: "❤️❤️❤️❤️ + ❤️❤️❤️❤️❤️❤️", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Double 5: 5 + 5 = ?", visual: "🟦🟦🟦🟦🟦 + 🟦🟦🟦🟦🟦", choices: ["9", "10", "11"], correct: "10", type: "number" },
    { q: "Anna has 7 books, gets 2 more. How many books?", visual: "📚📚📚📚📚📚📚 + 📚📚", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "What is the sum of 6 + 3?", visual: "🟫🟫🟫🟫🟫🟫 + 🟫🟫🟫", choices: ["8", "9", "10"], correct: "9", type: "number" },

    // Subtraction Concepts (25 questions)
    { q: "Elsa had 8 ice cubes. 3 melted. How many left?", visual: "🧊🧊🧊🧊🧊🧊🧊🧊 - 🧊🧊🧊", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "9 - 4 = ?", visual: "⭐⭐⭐⭐⭐⭐⭐⭐⭐ → cross out 4", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Olaf had 10 carrots. He ate 3. How many left?", visual: "🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕 - 🥕🥕🥕", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "7 - 2 = ?", visual: "🟡🟡🟡🟡🟡🟡🟡 → take away 2", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Anna had 6 flowers. She gave away 1. How many left?", visual: "🌸🌸🌸🌸🌸🌸 - 🌸", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "10 - 5 = ?", visual: "🟢🟢🟢🟢🟢🟢🟢🟢🟢🟢 → remove 5", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Subtract: 8 - 3", visual: "🔵🔵🔵🔵🔵🔵🔵🔵 - 🔵🔵🔵", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Take away 2 from 9: 9 - 2", visual: "🟨🟨🟨🟨🟨🟨🟨🟨🟨 ❌❌", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "Kristoff had 5 tools. He lost 2. How many left?", visual: "🔨🔨🔨🔨🔨 - 🔨🔨", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "6 - 6 = ?", visual: "🟦🟦🟦🟦🟦🟦 - 🟦🟦🟦🟦🟦🟦", choices: ["0", "1", "6"], correct: "0", type: "number" },
    { q: "There were 7 birds. 4 flew away. How many remained?", visual: "🐦🐦🐦🐦🐦🐦🐦 → 🐦🐦🐦🐦 fly away", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Subtract 1 from 10: 10 - 1", visual: "🔟 - 1️⃣", choices: ["8", "9", "10"], correct: "9", type: "number" },
    { q: "Elsa made 9 snowballs. 6 melted. How many left?", visual: "⚪⚪⚪⚪⚪⚪⚪⚪⚪ - ⚪⚪⚪⚪⚪⚪", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "8 - 0 = ?", visual: "🟧🟧🟧🟧🟧🟧🟧🟧 - ⭕", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "Anna picked 10 apples, gave away 4. How many left?", visual: "🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎 - 🍎🍎🍎🍎", choices: ["5", "6", "7"], correct: "6", type: "number" },
    { q: "Take 3 from 8: 8 - 3", visual: "❤️❤️❤️❤️❤️❤️❤️❤️ ❌❌❌", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Subtract: 7 - 7", visual: "⭐⭐⭐⭐⭐⭐⭐ - ⭐⭐⭐⭐⭐⭐⭐", choices: ["0", "1", "7"], correct: "0", type: "number" },
    { q: "5 - 1 = ?", visual: "🟪🟪🟪🟪🟪 → take 1 away", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Olaf had 6 buttons. 2 fell off. How many left?", visual: "🔘🔘🔘🔘🔘🔘 - 🔘🔘", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "9 - 9 = ?", visual: "🟫🟫🟫🟫🟫🟫🟫🟫🟫 - All", choices: ["0", "1", "9"], correct: "0", type: "number" },
    { q: "Count what's left: 6 - 2", visual: "🌟🌟🌟🌟🌟🌟 ❌❌", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Take 5 from 10: 10 - 5", visual: "🔟 - 5️⃣", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Sven had 8 sticks. He broke 4. How many whole sticks?", visual: "🦴🦴🦴🦴🦴🦴🦴🦴 - 🦴🦴🦴🦴", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "4 - 4 = ?", visual: "🟨🟨🟨🟨 - 🟨🟨🟨🟨", choices: ["0", "1", "4"], correct: "0", type: "number" },
    { q: "Anna had 7 crayons, lost 3. How many left?", visual: "🖍️🖍️🖍️🖍️🖍️🖍️🖍️ - 🖍️🖍️🖍️", choices: ["3", "4", "5"], correct: "4", type: "number" },

    // SECTION 2: MEASUREMENT AND DATA (100 questions - Priority area)
    // Sub-focus: Length, Time, Comparing/Sorting by attributes

    // Length and Measurement (40 questions)
    { q: "Which ribbon is LONGER?", visual: "A: ——————— <br> B: ———", choices: ["A", "B", "Same"], correct: "A", type: "text" },
    { q: "Which pencil is SHORTER?", visual: "🖊️ (long) vs ✏️ (short)", choices: ["First", "Second", "Same"], correct: "Second", type: "text" },
    { q: "Use paper clips to measure. How many?", visual: "📎📎📎 = pencil length", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Which tower is TALLER?", visual: "🧱🧱🧱 vs 🧱🧱🧱🧱🧱", choices: ["Left", "Right", "Same"], correct: "Right", type: "text" },
    { q: "Order from SHORTEST to LONGEST:", visual: "A:— B:——— C:———", choices: ["A,B,C", "C,B,A", "B,A,C"], correct: "A,B,C", type: "text" },
    { q: "How many cubes long?", visual: "🟫🟫🟫🟫 = ruler", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Which path is LONGER?", visual: "Path A: ↗️➡️ <br> Path B: ➡️➡️➡️", choices: ["A", "B", "Same"], correct: "B", type: "text" },
    { q: "Elsa's wand vs Anna's wand. Which is longer?", visual: "🪄 (5 units) vs 🪄 (3 units)", choices: ["Elsa's", "Anna's", "Same"], correct: "Elsa's", type: "text" },
    { q: "How many hands long is this table?", visual: "Table = ✋✋✋", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Which snake is SHORTEST?", visual: "🐍🐍 🐍🐍🐍🐍 🐍", choices: ["First", "Second", "Third"], correct: "Third", type: "text" },
    { q: "Measure with blocks. How long?", visual: "🧊🧊🧊🧊🧊 = ice slide", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Compare heights: Who is taller?", visual: "Anna 👧🏻 vs Elsa 👸🏼 (taller)", choices: ["Anna", "Elsa", "Same"], correct: "Elsa", type: "text" },
    { q: "Which line is LONGER?", visual: "———————— vs ————", choices: ["Top", "Bottom", "Same"], correct: "Top", type: "text" },
    { q: "How many steps across the room?", visual: "👣👣👣👣👣👣", choices: ["5", "6", "7"], correct: "6", type: "number" },
    { q: "Order these ropes: SHORT, MEDIUM, LONG", visual: "A:—— B:— C:———", choices: ["B,A,C", "C,A,B", "A,B,C"], correct: "B,A,C", type: "text" },
    { q: "Which icicle melted more (is shorter)?", visual: "Before: 🧊🧊🧊 After: 🧊🧊", choices: ["Before", "After", "Same"], correct: "After", type: "text" },
    { q: "Estimate: How many crayons long?", visual: "📏 ≈ 🖍️🖍️🖍️🖍️", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Compare arm spans: Whose is longer?", visual: "Kristoff 🙆‍♂️ vs Olaf ⛄", choices: ["Kristoff", "Olaf", "Same"], correct: "Kristoff", type: "text" },
    { q: "Measure the magic spell distance:", visual: "✨→→→→✨ = 4 units", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Which shadow is LONGER?", visual: "🌅 Short shadow vs 🌆 Long shadow", choices: ["Morning", "Evening", "Same"], correct: "Evening", type: "text" },
    { q: "How many foot lengths is the rug?", visual: "🦶🦶🦶🦶🦶 = rug", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Which bridge spans FARTHER?", visual: "Bridge A: ═══ Bridge B: ═════", choices: ["A", "B", "Same"], correct: "B", type: "text" },
    { q: "Sven's antlers vs reindeer toy. Which is longer?", visual: "🦌 (real) vs 🧸 (toy)", choices: ["Sven's", "Toy", "Same"], correct: "Sven's", type: "text" },
    { q: "How many blocks high is the castle?", visual: "🏰 = 🧱🧱🧱🧱🧱🧱", choices: ["5", "6", "7"], correct: "6", type: "number" },
    { q: "Which scarf keeps you warmer (longer)?", visual: "🧣 vs 🧣🧣", choices: ["First", "Second", "Same"], correct: "Second", type: "text" },
    { q: "Measure Anna's braid with ribbons:", visual: "💇‍♀️ = 🎀🎀🎀", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Compare distances: Home to school vs Home to park", visual: "🏠→🏫 (far) 🏠→🌳 (near)", choices: ["School", "Park", "Same"], correct: "School", type: "text" },
    { q: "Which carrot is LONGEST for Olaf?", visual: "🥕 🥕🥕 🥕🥕🥕", choices: ["First", "Second", "Third"], correct: "Third", type: "text" },
    { q: "How many hands wide is the door?", visual: "🚪 = ✋✋✋✋", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Which train is LONGER?", visual: "🚂🚃🚃 vs 🚂🚃", choices: ["First", "Second", "Same"], correct: "First", type: "text" },
    { q: "Measure the snowman's height:", visual: "⛄ = 🧊🧊🧊🧊🧊", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "Which river flows FARTHER?", visual: "River A: 〰️〰️ River B: 〰️", choices: ["A", "B", "Same"], correct: "A", type: "text" },
    { q: "Compare spoon lengths:", visual: "🥄 (small) vs 🥄 (large)", choices: ["Small", "Large", "Same"], correct: "Large", type: "text" },
    { q: "How many ice cubes tall?", visual: "📐 = 🧊🧊🧊🧊🧊🧊🧊", choices: ["6", "7", "8"], correct: "7", type: "number" },
    { q: "Which fishing line reaches DEEPER?", visual: "🎣 (short) vs 🎣 (long)", choices: ["First", "Second", "Same"], correct: "Second", type: "text" },
    { q: "Order by length: SMALL, MEDIUM, LARGE", visual: "🔧🔧🔧 🔧 🔧🔧", choices: ["2,3,1", "2,1,3", "3,1,2"], correct: "2,3,1", type: "text" },
    { q: "How many steps to cross the bridge?", visual: "🌉 = 👣👣👣👣👣👣👣👣", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "Which rope can tie the biggest package?", visual: "Package: 📦 Ropes: — vs ———", choices: ["Short", "Long", "Either"], correct: "Long", type: "text" },
    { q: "Measure Elsa's cape with paper clips:", visual: "👗 = 📎📎📎📎📎📎", choices: ["5", "6", "7"], correct: "6", type: "number" },
    { q: "Which ladder reaches HIGHER?", visual: "🪜 (3 steps) vs 🪜 (5 steps)", choices: ["First", "Second", "Same"], correct: "Second", type: "text" },

    // Time Concepts (35 questions)
    { q: "What time does the clock show?", visual: "🕐", choices: ["1:00", "12:00", "2:00"], correct: "1:00", type: "text" },
    { q: "It's 3:00. In 1 hour, what time will it be?", visual: "🕒 + 1 hour", choices: ["2:00", "4:00", "3:30"], correct: "4:00", type: "text" },
    { q: "Which takes LONGER: Brushing teeth or sleeping?", visual: "🪥 vs 😴", choices: ["Brushing", "Sleeping", "Same"], correct: "Sleeping", type: "text" },
    { q: "What time is shown?", visual: "🕕", choices: ["4:00", "5:00", "6:00"], correct: "5:00", type: "text" },
    { q: "Anna wakes up at 7:00. Show the time:", visual: "Morning wake up", choices: ["🕖", "🕐", "🕒"], correct: "🕖", type: "text" },
    { q: "Which activity takes MORE time?", visual: "🍽️ Eating vs 👀 Blinking", choices: ["Eating", "Blinking", "Same"], correct: "Eating", type: "text" },
    { q: "It's 2:00. What time was it 1 hour ago?", visual: "🕑 - 1 hour", choices: ["1:00", "3:00", "12:00"], correct: "1:00", type: "text" },
    { q: "When do we eat lunch?", visual: "🍽️ Lunch time", choices: ["Morning", "Noon", "Night"], correct: "Noon", type: "text" },
    { q: "What time does this clock show?", visual: "🕘", choices: ["8:00", "9:00", "10:00"], correct: "9:00", type: "text" },
    { q: "Elsa's bedtime is 8:00. Show the clock:", visual: "Bedtime 💤", choices: ["🕗", "🕐", "🕕"], correct: "🕗", type: "text" },
    { q: "Which takes LESS time: Counting to 10 or eating dinner?", visual: "🔢 vs 🍽️", choices: ["Counting", "Eating", "Same"], correct: "Counting", type: "text" },
    { q: "School starts at 9:00. What time?", visual: "🏫 School time", choices: ["🕘", "🕐", "🕒"], correct: "🕘", type: "text" },
    { q: "It's 6:00. In 30 minutes, what time?", visual: "🕕 + 30 min", choices: ["6:30", "7:00", "5:30"], correct: "6:30", type: "text" },
    { q: "Which happens at NIGHT?", visual: "🌙 Night time", choices: ["Breakfast", "Sleeping", "School"], correct: "Sleeping", type: "text" },
    { q: "What does this clock show?", visual: "🕛", choices: ["11:00", "12:00", "1:00"], correct: "12:00", type: "text" },
    { q: "Olaf melts in summer. What time of YEAR?", visual: "☀️ Summer", choices: ["Winter", "Spring", "Summer"], correct: "Summer", type: "text" },
    { q: "Which is FASTER: Running or walking?", visual: "🏃‍♀️ vs 🚶‍♀️", choices: ["Running", "Walking", "Same"], correct: "Running", type: "text" },
    { q: "Dinner time at Anna's house is 6:00. Show:", visual: "🍽️ Dinner", choices: ["🕕", "🕒", "🕘"], correct: "🕕", type: "text" },
    { q: "It's 10:00. What time will it be in 2 hours?", visual: "🕙 + 2 hours", choices: ["11:00", "12:00", "8:00"], correct: "12:00", type: "text" },
    { q: "When do we see the SUN?", visual: "☀️ Sunshine", choices: ["Night", "Day", "Always"], correct: "Day", type: "text" },
    { q: "What time is it?", visual: "🕐", choices: ["12:00", "1:00", "6:00"], correct: "1:00", type: "text" },
    { q: "Which season comes AFTER winter?", visual: "❄️ → ?", choices: ["Summer", "Fall", "Spring"], correct: "Spring", type: "text" },
    { q: "Kristoff works from 8:00 to 5:00. When does he start?", visual: "👷‍♂️ Work start", choices: ["🕗", "🕘", "🕔"], correct: "🕗", type: "text" },
    { q: "Which takes the LONGEST time?", visual: "⏰ Compare times", choices: ["Minute", "Hour", "Second"], correct: "Hour", type: "text" },
    { q: "Show 4:00 on the clock:", visual: "4 o'clock", choices: ["🕐", "🕓", "🕕"], correct: "🕓", type: "text" },
    { q: "When is it DARK outside?", visual: "🌃 Dark time", choices: ["Morning", "Noon", "Night"], correct: "Night", type: "text" },
    { q: "It's 1:00. What time was it 30 minutes ago?", visual: "🕐 - 30 min", choices: ["12:30", "1:30", "2:00"], correct: "12:30", type: "text" },
    { q: "Which day comes AFTER Monday?", visual: "Monday → ?", choices: ["Sunday", "Tuesday", "Wednesday"], correct: "Tuesday", type: "text" },
    { q: "Show 7:00 on the clock:", visual: "Morning time", choices: ["🕖", "🕐", "🕒"], correct: "🕖", type: "text" },
    { q: "Which is SHORTER: 1 minute or 1 hour?", visual: "⏰ vs 🕐", choices: ["Minute", "Hour", "Same"], correct: "Minute", type: "text" },
    { q: "What time for afternoon snack?", visual: "🍪 Snack time", choices: ["🕒", "🕘", "🕛"], correct: "🕒", type: "text" },
    { q: "Sven sleeps at night. When does he wake up?", visual: "🦌 Wake up", choices: ["Night", "Morning", "Noon"], correct: "Morning", type: "text" },
    { q: "Which month has Christmas? ❄️🎄", visual: "Christmas time", choices: ["July", "December", "March"], correct: "December", type: "text" },
    { q: "Show 11:00 on the clock:", visual: "11 o'clock", choices: ["🕐", "🕚", "🕛"], correct: "🕚", type: "text" },
    { q: "How many days in one WEEK?", visual: "📅 Week", choices: ["5", "6", "7"], correct: "7", type: "number" },

    // Sorting and Comparing (25 questions)
    { q: "Sort by SIZE: Which comes first?", visual: "🟨 🟪 🟦 (big→small)", choices: ["🟪", "🟦", "🟨"], correct: "🟪", type: "text" },
    { q: "Group these by COLOR:", visual: "🔴🟢🔵🔴🟢", choices: ["Size", "Color", "Shape"], correct: "Color", type: "text" },
    { q: "Which pile has MORE?", visual: "🍎🍎🍎 vs 🍎🍎🍎🍎🍎", choices: ["Left", "Right", "Same"], correct: "Right", type: "text" },
    { q: "Sort animals by WHERE they live:", visual: "🐟🦅🐕 (water/air/land)", choices: ["🐟🦅🐕", "🦅🐟🐕", "🐕🦅🐟"], correct: "🐟🦅🐕", type: "text" },
    { q: "Which group has FEWER items?", visual: "⭐⭐ vs ⭐⭐⭐⭐", choices: ["First", "Second", "Same"], correct: "First", type: "text" },
    { q: "Sort by WEIGHT: Light to Heavy", visual: "🪶🧱📝 (feather/brick/paper)", choices: ["🪶📝🧱", "🧱📝🪶", "📝🪶🧱"], correct: "🪶📝🧱", type: "text" },
    { q: "Group by NUMBER of legs:", visual: "🐕🐛🐦 (4/6/2 legs)", choices: ["Dogs", "Birds", "Bugs"], correct: "Dogs", type: "text" },
    { q: "Which basket holds MORE apples?", visual: "🧺: 🍎🍎🍎 vs 🧺: 🍎🍎", choices: ["First", "Second", "Same"], correct: "First", type: "text" },
    { q: "Sort shapes by NUMBER of sides:", visual: "△⬜○ (3/4/0)", choices: ["○△⬜", "△⬜○", "⬜△○"], correct: "○△⬜", type: "text" },
    { q: "Which jar has LESS candy?", visual: "🍯: 🍬🍬🍬🍬 vs 🍯: 🍬🍬", choices: ["Left", "Right", "Same"], correct: "Right", type: "text" },
    { q: "Group by TEXTURE: Smooth vs Rough", visual: "🧊🪨🔮 (ice/rock/crystal)", choices: ["🧊🔮🪨", "🪨🧊🔮", "🔮🧊🪨"], correct: "🧊🔮🪨", type: "text" },
    { q: "Compare amounts: Equal or Different?", visual: "🟢🟢🟢 vs 🟢🟢🟢", choices: ["Equal", "Different", "More"], correct: "Equal", type: "text" },
    { q: "Sort by TEMPERATURE: Cold to Hot", visual: "☀️🧊🔥 (sun/ice/fire)", choices: ["🧊☀️🔥", "🔥☀️🧊", "☀️🧊🔥"], correct: "🧊☀️🔥", type: "text" },
    { q: "Which tower has MORE blocks?", visual: "🧱🧱 vs 🧱🧱🧱🧱", choices: ["Left", "Right", "Same"], correct: "Right", type: "text" },
    { q: "Group these by SHAPE family:", visual: "⭐⚡⭐⚡⭐", choices: ["Stars", "Lightning", "Mixed"], correct: "Mixed", type: "text" },
    { q: "Compare: Which has EXACTLY 3 items?", visual: "🔴🔴 vs 🔵🔵🔵", choices: ["Red", "Blue", "Neither"], correct: "Blue", type: "text" },
    { q: "Sort by how they MOVE:", visual: "🐟🐦🚗 (swim/fly/drive)", choices: ["🐟🐦🚗", "🐦🐟🚗", "🚗🐦🐟"], correct: "🐟🐦🚗", type: "text" },
    { q: "Which line has MOST dots?", visual: "•• vs ••• vs •", choices: ["First", "Second", "Third"], correct: "Second", type: "text" },
    { q: "Group by what they DO:", visual: "🛏️🍽️📚 (sleep/eat/read)", choices: ["Sleep", "Read", "All"], correct: "All", type: "text" },
    { q: "Compare quantities: 4 vs 4", visual: "🟨🟨🟨🟨 vs 🟪🟪🟪🟪", choices: ["Yellow more", "Purple more", "Equal"], correct: "Equal", type: "text" },
    { q: "Sort by SIZE of opening:", visual: "🚪🔍⭕ (door/magnifying/circle)", choices: ["🔍⭕🚪", "🚪⭕🔍", "⭕🔍🚪"], correct: "🔍⭕🚪", type: "text" },
    { q: "Which group has NO items?", visual: "🍎 vs ⭕ vs 🍎🍎", choices: ["First", "Second", "Third"], correct: "Second", type: "text" },
    { q: "Sort by TIME of day used:", visual: "☀️🌙🕐 (sun/moon/clock)", choices: ["🌙☀️🕐", "☀️🕐🌙", "🕐☀️🌙"], correct: "☀️🕐🌙", type: "text" },
    { q: "Compare heights: Which is TALLEST?", visual: "🧒🧑👶", choices: ["Child", "Adult", "Baby"], correct: "Adult", type: "text" },
    { q: "Which collection is LARGEST?", visual: "🟢🟢🟢🟢🟢 vs 🔴🔴🔴", choices: ["Green", "Red", "Same"], correct: "Green", type: "text" },

    // SECTION 3: GEOMETRY (50 questions)
    // Sub-focus: Basic shapes and their attributes

    // Shape Identification (25 questions)
    { q: "What shape is this?", visual: "⭕", choices: ["Circle", "Square", "Triangle"], correct: "Circle", type: "text" },
    { q: "Which shape has 3 sides?", visual: "⭕⬜△", choices: ["Circle", "Square", "Triangle"], correct: "Triangle", type: "text" },
    { q: "Count the corners on this shape:", visual: "⬜", choices: ["3", "4", "0"], correct: "4", type: "number" },
    { q: "What shape is Elsa's window?", visual: "🪟 (square)", choices: ["Circle", "Square", "Triangle"], correct: "Square", type: "text" },
    { q: "Which shape rolls?", visual: "⚪🔷🔺", choices: ["Circle", "Diamond", "Triangle"], correct: "Circle", type: "text" },
    { q: "How many sides does a triangle have?", visual: "△", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "What shape is the sun?", visual: "☀️", choices: ["Circle", "Square", "Star"], correct: "Circle", type: "text" },
    { q: "Which shape has NO corners?", visual: "⭕⬜△", choices: ["Circle", "Square", "Triangle"], correct: "Circle", type: "text" },
    { q: "Count the sides of a square:", visual: "⬜", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "What shape is Anna's book?", visual: "📖 (rectangle)", choices: ["Circle", "Rectangle", "Triangle"], correct: "Rectangle", type: "text" },
    { q: "Which shape has the MOST sides?", visual: "△⬜⬟", choices: ["Triangle", "Square", "Pentagon"], correct: "Pentagon", type: "text" },
    { q: "What shape is a ball?", visual: "⚽", choices: ["Sphere", "Cube", "Cone"], correct: "Sphere", type: "text" },
    { q: "How many corners does a circle have?", visual: "⭕", choices: ["1", "2", "0"], correct: "0", type: "number" },
    { q: "What shape is an ice cube?", visual: "🧊", choices: ["Sphere", "Cube", "Cylinder"], correct: "Cube", type: "text" },
    { q: "Which is NOT a triangle?", visual: "△▲⬜", choices: ["First", "Second", "Third"], correct: "Third", type: "text" },
    { q: "What 3D shape is a can?", visual: "🥫", choices: ["Cube", "Cylinder", "Cone"], correct: "Cylinder", type: "text" },
    { q: "Count the sides of this shape:", visual: "⬟ (pentagon)", choices: ["4", "5", "6"], correct: "5", type: "number" },
    { q: "What shape is a party hat?", visual: "🎉", choices: ["Cube", "Cone", "Sphere"], correct: "Cone", type: "text" },
    { q: "Which shape has equal sides?", visual: "⬜ vs rectangle", choices: ["Square", "Rectangle", "Both"], correct: "Square", type: "text" },
    { q: "What shape is Olaf's head?", visual: "⛄ (circle)", choices: ["Square", "Circle", "Triangle"], correct: "Circle", type: "text" },
    { q: "How many faces does a cube have?", visual: "🧊", choices: ["4", "6", "8"], correct: "6", type: "number" },
    { q: "Which shape looks like a slice of pizza?", visual: "🍕", choices: ["Rectangle", "Circle", "Triangle"], correct: "Triangle", type: "text" },
    { q: "What shape has 6 sides?", visual: "⬡", choices: ["Pentagon", "Hexagon", "Octagon"], correct: "Hexagon", type: "text" },
    { q: "Count the edges of a triangle:", visual: "△", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "What 3D shape is a dice?", visual: "🎲", choices: ["Sphere", "Cube", "Pyramid"], correct: "Cube", type: "text" },

    // Shape Attributes and Comparisons (25 questions)
    { q: "Which shapes are the SAME?", visual: "⭕⬜⭕", choices: ["1 and 2", "1 and 3", "2 and 3"], correct: "1 and 3", type: "text" },
    { q: "What is DIFFERENT about these shapes?", visual: "🔴 (big) vs 🔴 (small)", choices: ["Color", "Size", "Shape"], correct: "Size", type: "text" },
    { q: "Which shape is BIGGER?", visual: "⬜ (large) vs ⬜ (small)", choices: ["First", "Second", "Same"], correct: "First", type: "text" },
    { q: "Group the circles together:", visual: "⭕⬜⭕△⭕", choices: ["1,3,5", "2,4", "All"], correct: "1,3,5", type: "text" },
    { q: "Which shape has MORE corners?", visual: "△ vs ⬜", choices: ["Triangle", "Square", "Same"], correct: "Square", type: "text" },
    { q: "What makes these shapes different?", visual: "🔵 vs 🔴", choices: ["Color", "Size", "Corners"], correct: "Color", type: "text" },
    { q: "Which is the SMALLEST shape?", visual: "⬜ (big) ⬜ (medium) ⬜ (tiny)", choices: ["First", "Second", "Third"], correct: "Third", type: "text" },
    { q: "How are these shapes the SAME?", visual: "🟥🟦 (both squares)", choices: ["Color", "Shape", "Size"], correct: "Shape", type: "text" },
    { q: "Which shape can STACK best?", visual: "⚪ vs 🧊", choices: ["Sphere", "Cube", "Same"], correct: "Cube", type: "text" },
    { q: "Count ALL the triangles:", visual: "△⬜△○△", choices: ["2", "3", "4"], correct: "3", type: "number" },
    { q: "Which shape would SLIDE down a hill fastest?", visual: "🧊 vs ⚪", choices: ["Cube", "Sphere", "Same"], correct: "Sphere", type: "text" },
    { q: "What do ALL squares have?", visual: "⬜ examples", choices: ["3 sides", "4 equal sides", "Curves"], correct: "4 equal sides", type: "text" },
    { q: "Which shape fits through a ROUND hole?", visual: "⭕ hole", choices: ["⬜", "⭕", "△"], correct: "⭕", type: "text" },
    { q: "Count shapes with STRAIGHT lines:", visual: "⭕⬜△", choices: ["1", "2", "3"], correct: "2", type: "number" },
    { q: "Which has MORE angles?", visual: "△ vs ⬜", choices: ["Triangle", "Square", "Same"], correct: "Square", type: "text" },
    { q: "What shape family do these belong to?", visual: "⬜🟦🟨 (all rectangles)", choices: ["Circles", "Rectangles", "Triangles"], correct: "Rectangles", type: "text" },
    { q: "Which shape CANNOT be flipped to look different?", visual: "⭕⬜△", choices: ["Circle", "Square", "Triangle"], correct: "Circle", type: "text" },
    { q: "Count the shapes with EXACTLY 4 sides:", visual: "△⬜⬟⬜", choices: ["1", "2", "3"], correct: "2", type: "number" },
    { q: "Which 3D shape has NO flat faces?", visual: "🧊 vs ⚪", choices: ["Cube", "Sphere", "Both"], correct: "Sphere", type: "text" },
    { q: "What is special about ALL circles?", visual: "⭕ varieties", choices: ["Have corners", "Are round", "Have sides"], correct: "Are round", type: "text" },
    { q: "Which shape would make the best wheel?", visual: "⭕⬜△", choices: ["Circle", "Square", "Triangle"], correct: "Circle", type: "text" },
    { q: "Count shapes that have NO straight edges:", visual: "⭕⬜🟦⭕", choices: ["1", "2", "3"], correct: "2", type: "number" },
    { q: "Which shapes are CONGRUENT (exactly the same)?", visual: "⬜⬜△", choices: ["1 and 2", "1 and 3", "2 and 3"], correct: "1 and 2", type: "text" },
    { q: "What makes a rectangle special?", visual: "▭", choices: ["All equal sides", "4 sides, opposite equal", "3 sides"], correct: "4 sides, opposite equal", type: "text" },
    { q: "Which shape would be hardest to push?", visual: "⚪ vs 🧊", choices: ["Sphere", "Cube", "Same"], correct: "Cube", type: "text" },

    // SECTION 4: ALGEBRA AND ALGEBRAIC THINKING (25 questions)
    // Sub-focus: Addition/subtraction relationships, patterns

    // Patterns and Relationships (15 questions)
    { q: "What comes next in the pattern?", visual: "❄️⭐❄️⭐❄️?", choices: ["❄️", "⭐", "⭕"], correct: "⭐", type: "text" },
    { q: "Complete the pattern:", visual: "🔴🟢🔴🟢🔴?", choices: ["🔴", "🟢", "🔵"], correct: "🟢", type: "text" },
    { q: "What's missing? 2, 4, 6, ?, 10", visual: "2️⃣4️⃣6️⃣?🔟", choices: ["7", "8", "9"], correct: "8", type: "number" },
    { q: "Which pattern rule fits?", visual: "🟨🟨⬜🟨🟨⬜", choices: ["AABAAB", "AABAA B", "AAB"], correct: "AAB", type: "text" },
    { q: "Continue: △⬜△⬜△?", visual: "Shape pattern", choices: ["△", "⬜", "⭕"], correct: "⬜", type: "text" },
    { q: "What number pattern? 1, 3, 5, 7...", visual: "Odd numbers", choices: ["Add 1", "Add 2", "Add 3"], correct: "Add 2", type: "text" },
    { q: "Complete: 🦋🐛🦋🐛?", visual: "Bug pattern", choices: ["🦋", "🐛", "🐝"], correct: "🦋", type: "text" },
    { q: "What's the rule? 5, 10, 15, 20", visual: "Number sequence", choices: ["Add 3", "Add 5", "Add 10"], correct: "Add 5", type: "text" },
    { q: "Next shape:", visual: "⭐⭐⭐⭐⭐?", choices: ["⭐", "⭕", "⬜"], correct: "⭐", type: "text" },
    { q: "Pattern: Big, Small, Big, Small, ?", visual: "🔴🔻🔴🔻?", choices: ["Big", "Small", "Medium"], correct: "Big", type: "text" },
    { q: "Complete: 10, 8, 6, 4, ?", visual: "Counting down", choices: ["2", "3", "5"], correct: "2", type: "number" },
    { q: "What comes next?", visual: "Anna, Elsa, Anna, Elsa, ?", choices: ["Anna", "Elsa", "Olaf"], correct: "Anna", type: "text" },
    { q: "Number pattern: 1, 1, 2, 2, ?", visual: "Doubling pattern", choices: ["1", "2", "3"], correct: "3", type: "number" },
    { q: "Shape pattern:", visual: "⬜△⬜△⬜?", choices: ["⬜", "△", "⭕"], correct: "△", type: "text" },
    { q: "What's missing: A, B, ?, D", visual: "Letter pattern", choices: ["A", "C", "E"], correct: "C", type: "text" },

    // Addition/Subtraction Relationships (10 questions)
    { q: "If 3 + 4 = 7, then 7 - 4 = ?", visual: "Fact family", choices: ["3", "4", "7"], correct: "3", type: "number" },
    { q: "Anna has some apples. She gives away 2 and has 5 left. How many did she start with?", visual: "? - 2 = 5", choices: ["3", "7", "8"], correct: "7", type: "number" },
    { q: "If 6 + 2 = 8, what is 8 - 6?", visual: "Related facts", choices: ["1", "2", "6"], correct: "2", type: "number" },
    { q: "What number makes this true? 5 + ? = 9", visual: "5 + __ = 9", choices: ["3", "4", "5"], correct: "4", type: "number" },
    { q: "Elsa knows 2 + 8 = 10. What is 10 - 8?", visual: "Inverse operation", choices: ["2", "8", "10"], correct: "2", type: "number" },
    { q: "Complete: ? + 3 = 6", visual: "Missing addend", choices: ["2", "3", "9"], correct: "3", type: "number" },
    { q: "If 4 + 5 = 9, then 9 - ? = 4", visual: "Fact family triangle", choices: ["4", "5", "9"], correct: "5", type: "number" },
    { q: "Olaf had 8 buttons. Some fell off. He has 6 left. How many fell?", visual: "8 - ? = 6", choices: ["2", "6", "8"], correct: "2", type: "number" },
    { q: "What makes this equal? 7 = 3 + ?", visual: "Balance equation", choices: ["3", "4", "10"], correct: "4", type: "number" },
    { q: "If you know 1 + 9 = 10, what is 9 + 1?", visual: "Commutative property", choices: ["9", "10", "19"], correct: "10", type: "number" }
];

module.exports = mathQuestions;